import type { Photoshoot } from "./types";

// Photoshoot Packages — Egypt Eye's signature products.

export const photoshoots: Photoshoot[] = [
  {
    slug: "exclusive-pyramids-photoshoot",
    title: "Exclusive Pyramids Photoshoot",
    duration: "1–2 hours",
    rating: { score: 5, count: 4 },
    price: { amount: 75, originalAmount: 100, currency: "USD" },
    locations: ["Giza Pyramids", "Nine Pyramids View"],
    imageLabel: "Pyramids Photoshoot",
    imageTone: "giza",
    image: "/photos/pexels-36505454.jpg",
    description:
      "A private, professionally directed photoshoot at the Pyramids of Giza — built for travelers who want cinematic, Instagram-ready memories, not just snapshots.",
    goodFor: ["Solo travelers", "Couples", "Families", "Influencers & content creators"],
    included: [
      "Private professional photographer",
      "Professional camera equipment",
      "Private transportation",
      "Parking & road tolls",
      "80+ edited pictures",
      "24-hour follow-up service",
    ],
    addOns: [
      "Professional video Reel",
      "Arabian horse photography",
      "Camel experience",
      "Group photoshoot",
    ],
    delivery: [
      "80+ edited pictures",
      "Raw, unedited photos the same day",
      "Optional larger gallery: 100+ high-resolution edited images within 5 days",
    ],
    destinations: ["Giza"],
  },
  {
    slug: "flying-dress-photoshoot",
    title: "Sand Dunes Flying Dress Photoshoot",
    duration: "1 hour",
    rating: { score: 5, count: 1 },
    price: { amount: 199, originalAmount: 250, currency: "USD" },
    locations: ["Sand Dunes"],
    imageLabel: "Flying Dress in the Sand Dunes",
    imageTone: "desert",
    image: "/photos/pexels-8037495.jpg",
    description:
      "Egypt's first Flying Dress experience — a dramatic, editorial-style shoot in a flowing dress of your chosen color, out among the desert's sand dunes, directed by our photographers at secret, uncrowded locations away from the crowds.",
    goodFor: [
      "Solo travelers",
      "Engagements & proposals",
      "Couples",
      "Fashion shoots",
      "Personal content",
    ],
    included: [
      "Flying dress in your chosen color",
      "Professional photographer & posing direction",
      "Private transportation, pickup and return",
      "Secret, less crowded locations",
      "Edited images",
      "Egyptian souvenir",
    ],
    addOns: ["High-end retouching upgrade"],
    delivery: ["Professionally edited image gallery", "Optional high-end retouching"],
    destinations: ["Giza"],
  },
  {
    slug: "fayoum-flying-dress-photoshoot",
    title: "Fayoum Flying Dress Photoshoot",
    duration: "1 hour",
    rating: { score: 5, count: 1 },
    price: { amount: 219, originalAmount: 270, currency: "USD" },
    locations: ["Fayoum — Wadi El Rayan & the Magic Lake"],
    imageLabel: "Flying Dress in Fayoum",
    imageTone: "desert",
    image: "/photos/pexels-38498244.jpg",
    description:
      "The Flying Dress experience out at Fayoum's Wadi El Rayan and the Magic Lake — a flowing dress of your chosen color against the oasis's water and dunes, directed by our photographers away from the crowds.",
    goodFor: [
      "Solo travelers",
      "Engagements & proposals",
      "Couples",
      "Fashion shoots",
      "Personal content",
    ],
    included: [
      "Flying dress in your chosen color",
      "Professional photographer & posing direction",
      "Private transportation, pickup and return from Cairo",
      "Wadi El Rayan & Magic Lake access",
      "Edited images",
      "Egyptian souvenir",
    ],
    addOns: ["High-end retouching upgrade"],
    delivery: ["Professionally edited image gallery", "Optional high-end retouching"],
    destinations: ["Fayoum"],
  },
  {
    slug: "jumping-horse-photoshoot",
    title: "Jumping Horse Photoshoot",
    duration: "1–2 hours",
    rating: { score: 5, count: 2 },
    price: { amount: 120, originalAmount: 150, currency: "USD" },
    locations: ["Giza Pyramids", "Nine Pyramids View"],
    imageLabel: "Jumping Horse at the Pyramids",
    imageTone: "giza",
    image: "/photos/pexels-38513972.jpg",
    description:
      "A high-energy, action photoshoot at the Nine Pyramids View — you and a trained horse mid-jump against the Pyramids, directed and timed by our photographers for the shot.",
    goodFor: ["Solo travelers", "Couples", "Equestrians", "Influencers & content creators"],
    included: [
      "Private transfer to the Pyramids area",
      "Access to the Nine Pyramids View",
      "Trained horse & professional handler",
      "Private professional photographer",
      "Edited images",
    ],
    addOns: ["Horse riding experience through the desert"],
    delivery: ["Professionally edited image gallery", "Raw, unedited photos the same day"],
    destinations: ["Giza"],
  },
  {
    slug: "running-horse-video-jumping-horse-photoshoot",
    title: "Running Horse Video + Jumping Horse Photoshoot",
    duration: "1–2 hours",
    rating: { score: 5, count: 1 },
    price: { amount: 160, originalAmount: 195, currency: "USD" },
    locations: ["Giza Pyramids", "Nine Pyramids View"],
    imageLabel: "Running Horse at the Pyramids",
    imageTone: "giza",
    image: "/photos/pexels-38513972.jpg",
    description:
      "The Jumping Horse Photoshoot at the Nine Pyramids View, paired with a cinematic running-horse video — the horse in full gallop with the Pyramids in the background, filmed and directed by our team.",
    goodFor: ["Solo travelers", "Couples", "Equestrians", "Influencers & content creators"],
    included: [
      "Private transfer to the Pyramids area",
      "Access to the Nine Pyramids View",
      "Trained horse & professional handler",
      "Private professional photographer",
      "Jumping horse photoshoot with the Pyramids",
      "Edited images",
    ],
    addOns: ["Running horse video experience with the Pyramids in the background"],
    delivery: ["Professionally edited image gallery", "Raw, unedited photos the same day"],
    destinations: ["Giza"],
  },
  {
    slug: "pyramids-proposal-romance-setup",
    title: "Pyramids Proposal Romance Setup",
    duration: "1 hour",
    rating: null,
    price: { amount: 150, currency: "USD" },
    locations: ["Giza Pyramids", "Nine Pyramids View"],
    imageLabel: "Pyramids Proposal Setup",
    imageTone: "giza",
    image: "/photos/pexels-28682219.jpg",
    description:
      "A private, beautifully styled proposal setup overlooking the Pyramids of Giza — romantic decorations, flowers, and candlelight, arranged and ready before you arrive, so all that's left is the moment itself. Pricing depends on the setup and style you choose. This is enquiry-only — our team confirms your setup, styling, and pricing directly with you.",
    goodFor: ["Engagements & proposals", "Couples"],
    included: [
      "Romantic decorations",
      "Flowers and floral arrangements",
      "Candles and romantic lighting",
      "Elegant proposal setup",
      "Personalized decoration options",
      "Professional setup completed before you arrive",
    ],
    addOns: ["Pyramids Proposal Photoshoot — professional photography & fully edited photos"],
    delivery: [
      "The setup fully styled and ready before you arrive",
      "Optional: professional photography and a fully edited photo gallery with the Pyramids Proposal Photoshoot add-on",
    ],
    destinations: ["Giza"],
  },
];

export function getPhotoshootBySlug(slug: string) {
  return photoshoots.find((p) => p.slug === slug);
}
