import type { Tour } from "./types";

// Popular Tours — edit durations, ratings, itineraries, and pricing here.
// price.amount = null means "Contact for pricing" (shown as "Get a Quote").

export const tours: Tour[] = [
  {
    slug: "1-day-giza-tour",
    title: "1 Day Giza Tour: Exploring Ancient Wonders",
    tagline: "Pyramids, Sphinx, and a free private photoshoot — all in one day.",
    category: "one-day",
    duration: "8 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Giza"],
    rating: { score: 4.98, count: 8 },
    badge: "Free Private Photoshoot",
    imageLabel: "Giza Pyramids",
    imageTone: "giza",
    description:
      "Our signature day trip combines the Giza Pyramids, the Great Sphinx, and the Valley Temple with a camel ride, the iconic Nine Pyramids View, and a complimentary professional photoshoot — finished off with an Egyptian lunch and a perfume and essential oils experience.",
    highlights: [
      "Giza Pyramids & Great Sphinx",
      "Valley Temple",
      "Camel experience",
      "Nine Pyramids View",
      "Complimentary professional photoshoot",
      "Egyptian lunch",
      "Perfume & essential oils experience",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Professional content creator",
      "Entrance fees",
      "Lunch",
      "Bottled water",
      "Shopping tours",
      "Taxes and service charges",
    ],
    excluded: ["Extras not mentioned", "Tips", "Hotels", "Flights"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "fayoum-nature-tour",
    title: "Fayoum: The Beautiful Nature of Egypt",
    tagline: "Waterfalls, desert lakes, and Egypt's quieter, greener side.",
    category: "one-day",
    duration: "1 day / 12 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Fayoum"],
    rating: null,
    imageLabel: "Fayoum Oasis",
    imageTone: "desert",
    description:
      "Escape the city for Fayoum's dramatic landscapes — Wadi El Rayan's waterfalls, golden dunes, and the Magic Lake — a favorite for travelers who want Egypt's natural beauty alongside its ancient history.",
    highlights: [
      "Wadi El Rayan waterfalls",
      "Magic Lake",
      "Desert scenery & sand dunes",
      "Private Egyptologist guide",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking guide",
      "Lunch",
      "Bottled water",
      "Entrance fees",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Optional activities"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "red-sea-relaxation",
    title: "Egypt's Relaxation Mood: Red Sea",
    tagline: "Turquoise water, white sand, and nothing on the agenda.",
    category: "one-day",
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Red Sea"],
    rating: null,
    imageLabel: "Red Sea Coast",
    imageTone: "redsea",
    description:
      "A slower-paced day built around the Red Sea's calm, clear water — swimming, snorkeling, and lounging on a private beach, with the option to add our Luxe Yacht experience.",
    highlights: [
      "Private beach access",
      "Swimming & snorkeling",
      "Optional Red Sea Luxe Yacht add-on",
      "Private transportation",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Bottled water",
      "Beach access",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Water sports equipment rental"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "3-day-cairo-giza",
    title: "Three-Day Excursion: Cairo & Giza",
    tagline: "A complete first taste of Egypt's ancient and modern capital.",
    category: "multi-day",
    duration: "3 days",
    lengthDays: 3,
    cities: 1,
    destinations: ["Cairo", "Giza"],
    rating: null,
    imageLabel: "Cairo & Giza",
    imageTone: "giza",
    description:
      "Three unhurried days across Cairo and Giza — pyramids, museums, Islamic and Coptic Cairo, and the bazaars of Khan el-Khalili — with a private Egyptologist throughout.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Grand Egyptian Museum / Egyptian Museum",
      "Coptic Cairo & Khan el-Khalili",
      "Professional photoshoot",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch daily",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "siwa-oasis",
    title: "Desert Dreams: Siwa Oasis",
    tagline: "Egypt's most remote oasis — salt lakes, dunes, and starlit skies.",
    category: "multi-day",
    duration: "3 days",
    lengthDays: 3,
    cities: 1,
    destinations: ["Siwa Oasis"],
    rating: null,
    imageLabel: "Siwa Oasis",
    imageTone: "desert",
    description:
      "A journey deep into the Great Sand Sea to Siwa — natural springs, salt lakes, the Oracle Temple, and some of the darkest, clearest night skies in Egypt.",
    highlights: [
      "Great Sand Sea",
      "Salt lakes & natural springs",
      "Oracle Temple",
      "ATV & 4x4 desert safari",
    ],
    included: [
      "Private air-conditioned transfers",
      "Private English-speaking guide",
      "Entrance fees",
      "Accommodation as arranged",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "3-days-jordan",
    title: "3 Days Exploring the Wonders of Jordan",
    tagline: "Wadi Rum, Petra, and the Dead Sea in one unforgettable trip.",
    category: "jordan",
    duration: "3 days",
    lengthDays: 3,
    cities: 3,
    destinations: ["Wadi Rum", "Petra", "Dead Sea"],
    rating: null,
    imageLabel: "Petra, Jordan",
    imageTone: "jordan",
    description:
      "From the rose-red city of Petra to a 4x4 Jeep safari through Wadi Rum's Martian landscape, finishing with a float in the Dead Sea — Jordan's essential highlights, privately guided.",
    highlights: [
      "Petra — the Treasury & Siq",
      "Wadi Rum 4x4 Jeep safari",
      "Dead Sea floating experience",
      "Airport meet & greet",
    ],
    included: [
      "Airport meet & greet",
      "Guest relations assistance",
      "Private air-conditioned transfers",
      "English-speaking guide",
      "4x4 Jeep Safari",
      "Entrance tickets",
    ],
    excluded: [
      "Flights",
      "Hotels",
      "Egypt visa",
      "Optional tours",
      "Personal expenses",
      "Tips",
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "5-day-giza-cairo-alexandria",
    title: "5-Day Egypt: Giza, Cairo & Alexandria",
    tagline: "Pyramids, the capital, and the Mediterranean coast.",
    category: "multi-day",
    duration: "5 days",
    lengthDays: 5,
    cities: 2,
    destinations: ["Cairo", "Giza", "Alexandria"],
    rating: { score: 5, count: 1 },
    imageLabel: "Alexandria Coast",
    imageTone: "nile",
    description:
      "Combine Cairo and Giza's ancient highlights with a day trip to Alexandria's Mediterranean charm — the Citadel of Qaitbay, Bibliotheca Alexandrina, and the Catacombs of Kom el Shoqafa.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Egyptian Museum",
      "Citadel of Qaitbay",
      "Bibliotheca Alexandrina",
      "Professional photoshoot",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch daily",
      "Professional photoshoot",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "6-day-cairo-giza-luxor",
    title: "6 Days: Cairo, Giza & Luxor",
    tagline: "Pyramids, temples, and the Valley of the Kings.",
    category: "multi-day",
    duration: "6 days",
    lengthDays: 6,
    cities: 3,
    destinations: ["Cairo", "Giza", "Luxor"],
    rating: { score: 4.95, count: 8 },
    imageLabel: "Luxor Temple",
    imageTone: "luxor",
    description:
      "Six days across Cairo, Giza, and Luxor — the Nine Pyramids photoshoot, Coptic Cairo, Khan el-Khalili, and the temples and tombs of ancient Thebes on both banks of the Nile.",
    highlights: [
      "Nine Pyramids professional photoshoot",
      "Coptic Cairo & Khan el-Khalili",
      "Avenue of Sphinxes & Karnak Temple",
      "Valley of the Kings & Hatshepsut Temple",
      "Optional hot-air balloon over Luxor",
    ],
    included: [
      "Nine Pyramids professional photoshoot",
      "Professional content creator",
      "Sightseeing transportation",
      "Lunch",
      "Camel ride",
      "English-speaking tour manager",
      "Entrance fees",
    ],
    excluded: [
      "Egypt visa",
      "Hotels",
      "Flights",
      "Personal spending",
      "Optional activities",
      "Tips",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Cairo", description: "Meet and greet, transfer, and welcome briefing." },
      {
        day: 2,
        title: "Giza",
        description:
          "Giza Pyramids, Sphinx, Valley Temple, professional photoshoot, lunch, and a perfume & essential oils experience.",
      },
      {
        day: 3,
        title: "Cairo",
        description:
          "Coptic Cairo, the Hanging Church, the National Museum of Egyptian Civilization, Royal Mummies, and Khan el-Khalili bazaar.",
      },
      {
        day: 4,
        title: "Luxor — East Bank",
        description: "Avenue of Sphinxes, Karnak Temple complex, and Luxor Temple.",
      },
      {
        day: 5,
        title: "Luxor — West Bank",
        description:
          "Optional hot-air balloon at sunrise, Valley of the Kings, Hatshepsut Temple, an alabaster and marble workshop, and the Colossi of Memnon.",
      },
      { day: 6, title: "Departure", description: "Transfer to the airport for your onward flight." },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "8-day-essential-egypt-nile-cruise",
    title: "8 Days Essential Egypt + 5-Day Nile Cruise",
    tagline: "Cairo and Giza, then five days cruising the Nile in 5-star comfort.",
    category: "multi-day",
    duration: "8 days",
    lengthDays: 8,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Aswan"],
    rating: { score: 5, count: 18 },
    imageLabel: "Nile Cruise",
    imageTone: "nile",
    description:
      "Our most complete Egypt itinerary — Cairo and Giza's ancient wonders followed by a 5-day Nile Cruise from Luxor to Aswan, visiting Karnak, the Valley of the Kings, Philae Temple, and the Aswan High Dam along the way.",
    highlights: [
      "Nine Pyramids professional photoshoot",
      "5-star Nile Cruise, Luxor to Aswan",
      "Karnak & Luxor Temples",
      "Valley of the Kings",
      "Philae Temple & the Unfinished Obelisk",
    ],
    included: [
      "Professional Nine Pyramids photoshoot",
      "Professional content creator",
      "Air-conditioned sightseeing transport",
      "Lunch",
      "Camel ride",
      "English-speaking tour manager",
      "Entrance fees",
      "5-star Nile Cruise accommodation",
      "Meals aboard the cruise",
    ],
    excluded: [
      "Egypt visa",
      "Cairo hotels",
      "Flights",
      "Personal spending",
      "Optional activities",
      "Tips",
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "10-day-private-luxurious-trip",
    title: "10-Day Private & Luxurious Trip",
    tagline: "The full country, at a private, unhurried, five-star pace.",
    category: "multi-day",
    duration: "10 days",
    lengthDays: 10,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Aswan"],
    rating: { score: 3.67, count: 3 },
    badge: "Customizable",
    imageLabel: "Aswan Sunset",
    imageTone: "nile",
    description:
      "Ten fully private days combining Cairo and Giza, a Nile Cruise, and time built in for photoshoots, relaxation, and any experience you'd like to add — designed around your pace, not a fixed group schedule.",
    highlights: [
      "Fully private throughout",
      "Nine Pyramids photoshoot",
      "5-star Nile Cruise",
      "Flexible, customizable pacing",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Entrance fees",
      "5-star Nile Cruise accommodation",
      "Meals as specified",
    ],
    excluded: ["Egypt visa", "Cairo hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "epic-8-day-egypt-escapade",
    title: "Epic 8-Day Egypt Escapade",
    tagline: "Pyramids, temples, desert, and Red Sea — Egypt's greatest hits.",
    category: "multi-day",
    duration: "8 days",
    lengthDays: 8,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Red Sea"],
    rating: null,
    imageLabel: "Egypt Escapade",
    imageTone: "desert",
    description:
      "A fast-paced, highlight-packed week across Egypt's icons — the Pyramids, Luxor's temples and tombs, and a few days of Red Sea relaxation to close out the trip.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Luxor's East & West Banks",
      "Red Sea relaxation days",
      "Professional photoshoot",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Entrance fees",
      "Lunch on touring days",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
];

export function getTourBySlug(slug: string) {
  return tours.find((t) => t.slug === slug);
}
