import type { Tour } from "./types";

// Popular Tours — edit durations, ratings, itineraries, and pricing here.
// price.amount = null means "Contact for pricing" (shown as "Get a Quote").

export const tours: Tour[] = [
  {
    slug: "1-day-giza-tour",
    title: "1 Day Giza Tour: Exploring Ancient Wonders",
    tagline: "Pyramids, Sphinx, and a free private photoshoot — all in one day.",
    category: "one-day",
    featured: true,
    travelStyle: ["Cultural", "Family"],
    duration: "8 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Giza"],
    rating: { score: 4.98, count: 8 },
    badge: "Free Private Photoshoot",
    imageLabel: "Giza Pyramids",
    imageTone: "giza",
    description:
      "Our signature day trip combines the Giza Pyramids, the Great Sphinx, and the Valley Temple with a camel ride, the iconic Nine Pyramids View, and a complimentary professional photoshoot — finished off with an Egyptian lunch and a perfume and essential oils experience.",
    highlights: [
      "Giza Pyramids & Great Sphinx",
      "Valley Temple",
      "Camel experience",
      "Nine Pyramids View",
      "Complimentary professional photoshoot",
      "Egyptian lunch",
      "Perfume & essential oils experience",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Professional content creator",
      "Entrance fees",
      "Lunch",
      "Bottled water",
      "Shopping tours",
      "Taxes and service charges",
    ],
    excluded: ["Extras not mentioned", "Tips", "Hotels", "Flights"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "fayoum-nature-tour",
    title: "Fayoum: The Beautiful Nature of Egypt",
    tagline: "Waterfalls, desert lakes, and Egypt's quieter, greener side.",
    category: "one-day",
    travelStyle: ["Slow Travel", "Adventure"],
    duration: "1 day / 12 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Fayoum"],
    rating: null,
    imageLabel: "Fayoum Oasis",
    imageTone: "desert",
    description:
      "Escape the city for Fayoum's dramatic landscapes — Wadi El Rayan's waterfalls, golden dunes, and the Magic Lake — a favorite for travelers who want Egypt's natural beauty alongside its ancient history.",
    highlights: [
      "Wadi El Rayan waterfalls",
      "Magic Lake",
      "Desert scenery & sand dunes",
      "Private Egyptologist guide",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking guide",
      "Lunch",
      "Bottled water",
      "Entrance fees",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Optional activities"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "red-sea-relaxation",
    title: "Egypt's Relaxation Mood: Red Sea",
    tagline: "Turquoise water, white sand, and nothing on the agenda.",
    category: "one-day",
    featured: true,
    travelStyle: ["Slow Travel", "Honeymoon"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Red Sea"],
    rating: null,
    imageLabel: "Red Sea Coast",
    imageTone: "redsea",
    description:
      "A slower-paced day built around the Red Sea's calm, clear water — swimming, snorkeling, and lounging on a private beach, with the option to add our Luxe Yacht experience.",
    highlights: [
      "Private beach access",
      "Swimming & snorkeling",
      "Optional Red Sea Luxe Yacht add-on",
      "Private transportation",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Bottled water",
      "Beach access",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Water sports equipment rental"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "3-day-cairo-giza",
    title: "Three-Day Excursion: Cairo & Giza",
    tagline: "A complete first taste of Egypt's ancient and modern capital.",
    category: "multi-day",
    travelStyle: ["Cultural", "Family"],
    duration: "3 days",
    lengthDays: 3,
    cities: 1,
    destinations: ["Cairo", "Giza"],
    rating: null,
    imageLabel: "Cairo & Giza",
    imageTone: "giza",
    description:
      "Three unhurried days across Cairo and Giza — pyramids, museums, Islamic and Coptic Cairo, and the bazaars of Khan el-Khalili — with a private Egyptologist throughout.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Grand Egyptian Museum / Egyptian Museum",
      "Coptic Cairo & Khan el-Khalili",
      "Professional photoshoot",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch daily",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "siwa-oasis",
    title: "Desert Dreams: Siwa Oasis",
    tagline: "Egypt's most remote oasis — salt lakes, dunes, and starlit skies.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "3 days",
    lengthDays: 3,
    cities: 1,
    destinations: ["Siwa Oasis"],
    rating: null,
    imageLabel: "Siwa Oasis",
    imageTone: "desert",
    description:
      "A journey deep into the Great Sand Sea to Siwa — natural springs, salt lakes, the Oracle Temple, and some of the darkest, clearest night skies in Egypt.",
    highlights: [
      "Great Sand Sea",
      "Salt lakes & natural springs",
      "Oracle Temple",
      "ATV & 4x4 desert safari",
    ],
    included: [
      "Private air-conditioned transfers",
      "Private English-speaking guide",
      "Entrance fees",
      "Accommodation as arranged",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "3-days-jordan",
    title: "3 Days Exploring the Wonders of Jordan",
    tagline: "Wadi Rum, Petra, and the Dead Sea in a single private itinerary.",
    category: "jordan",
    featured: true,
    travelStyle: ["Adventure", "Cultural", "Private"],
    duration: "3 days",
    lengthDays: 3,
    cities: 3,
    destinations: ["Wadi Rum", "Petra", "Dead Sea"],
    rating: null,
    imageLabel: "Petra, Jordan",
    imageTone: "jordan",
    description:
      "From the rose-red city of Petra to a 4x4 Jeep safari through Wadi Rum's Martian landscape, finishing with a float in the Dead Sea — Jordan's essential highlights, privately guided.",
    highlights: [
      "Petra — the Treasury & Siq",
      "Wadi Rum 4x4 Jeep safari",
      "Dead Sea floating experience",
      "Airport meet & greet",
    ],
    included: [
      "Airport meet & greet",
      "Guest relations assistance",
      "Private air-conditioned transfers",
      "English-speaking guide",
      "4x4 Jeep Safari",
      "Entrance tickets",
    ],
    excluded: [
      "Flights",
      "Hotels",
      "Egypt visa",
      "Optional tours",
      "Personal expenses",
      "Tips",
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "5-day-giza-cairo-alexandria",
    title: "5-Day Egypt: Giza, Cairo & Alexandria",
    tagline: "Pyramids, the capital, and the Mediterranean coast.",
    category: "multi-day",
    travelStyle: ["Cultural"],
    duration: "5 days",
    lengthDays: 5,
    cities: 2,
    destinations: ["Cairo", "Giza", "Alexandria"],
    rating: { score: 5, count: 1 },
    imageLabel: "Alexandria Coast",
    imageTone: "nile",
    description:
      "Combine Cairo and Giza's ancient highlights with a day trip to Alexandria's Mediterranean charm — the Citadel of Qaitbay, Bibliotheca Alexandrina, and the Catacombs of Kom el Shoqafa.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Egyptian Museum",
      "Citadel of Qaitbay",
      "Bibliotheca Alexandrina",
      "Professional photoshoot",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch daily",
      "Professional photoshoot",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "6-day-cairo-giza-luxor",
    title: "6 Days: Cairo, Giza & Luxor",
    tagline: "Pyramids, temples, and the Valley of the Kings.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Cultural", "Private"],
    duration: "6 days",
    lengthDays: 6,
    cities: 3,
    destinations: ["Cairo", "Giza", "Luxor"],
    rating: { score: 4.95, count: 8 },
    imageLabel: "Luxor Temple",
    imageTone: "luxor",
    description:
      "Six days across Cairo, Giza, and Luxor — the Nine Pyramids photoshoot, Coptic Cairo, Khan el-Khalili, and the temples and tombs of ancient Thebes on both banks of the Nile.",
    highlights: [
      "Nine Pyramids professional photoshoot",
      "Coptic Cairo & Khan el-Khalili",
      "Avenue of Sphinxes & Karnak Temple",
      "Valley of the Kings & Hatshepsut Temple",
      "Optional hot-air balloon over Luxor",
    ],
    included: [
      "Nine Pyramids professional photoshoot",
      "Professional content creator",
      "Sightseeing transportation",
      "Lunch",
      "Camel ride",
      "English-speaking tour manager",
      "Entrance fees",
    ],
    excluded: [
      "Egypt visa",
      "Hotels",
      "Flights",
      "Personal spending",
      "Optional activities",
      "Tips",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Cairo", description: "Meet and greet, transfer, and welcome briefing." },
      {
        day: 2,
        title: "Giza",
        description:
          "Giza Pyramids, Sphinx, Valley Temple, professional photoshoot, lunch, and a perfume & essential oils experience.",
      },
      {
        day: 3,
        title: "Cairo",
        description:
          "Coptic Cairo, the Hanging Church, the National Museum of Egyptian Civilization, Royal Mummies, and Khan el-Khalili bazaar.",
      },
      {
        day: 4,
        title: "Luxor — East Bank",
        description: "Avenue of Sphinxes, Karnak Temple complex, and Luxor Temple.",
      },
      {
        day: 5,
        title: "Luxor — West Bank",
        description:
          "Optional hot-air balloon at sunrise, Valley of the Kings, Hatshepsut Temple, an alabaster and marble workshop, and the Colossi of Memnon.",
      },
      { day: 6, title: "Departure", description: "Transfer to the airport for your onward flight." },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "8-day-essential-egypt-nile-cruise",
    title: "8 Days Essential Egypt + 5-Day Nile Cruise",
    tagline: "Cairo and Giza, then five days cruising the Nile in 5-star comfort.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Private", "Cultural"],
    duration: "8 days",
    lengthDays: 8,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Aswan"],
    rating: { score: 5, count: 18 },
    imageLabel: "Nile Cruise",
    imageTone: "nile",
    description:
      "Our most complete Egypt itinerary — Cairo and Giza's ancient wonders followed by a 5-day Nile Cruise from Luxor to Aswan, visiting Karnak, the Valley of the Kings, Philae Temple, and the Aswan High Dam along the way.",
    highlights: [
      "Nine Pyramids professional photoshoot",
      "5-star Nile Cruise, Luxor to Aswan",
      "Karnak & Luxor Temples",
      "Valley of the Kings",
      "Philae Temple & the Unfinished Obelisk",
    ],
    included: [
      "Professional Nine Pyramids photoshoot",
      "Professional content creator",
      "Air-conditioned sightseeing transport",
      "Lunch",
      "Camel ride",
      "English-speaking tour manager",
      "Entrance fees",
      "5-star Nile Cruise accommodation",
      "Meals aboard the cruise",
    ],
    excluded: [
      "Egypt visa",
      "Cairo hotels",
      "Flights",
      "Personal spending",
      "Optional activities",
      "Tips",
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "10-day-private-luxurious-trip",
    title: "10-Day Private & Luxurious Trip",
    tagline: "The full country, at a private, unhurried, five-star pace.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Luxury", "Private", "Honeymoon"],
    duration: "10 days",
    lengthDays: 10,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Aswan"],
    rating: { score: 3.67, count: 3 },
    badge: "Customizable",
    imageLabel: "Aswan Sunset",
    imageTone: "nile",
    description:
      "Ten fully private days combining Cairo and Giza, a Nile Cruise, and time built in for photoshoots, relaxation, and any experience you'd like to add — designed around your pace, not a fixed group schedule.",
    highlights: [
      "Fully private throughout",
      "Nine Pyramids photoshoot",
      "5-star Nile Cruise",
      "Flexible, customizable pacing",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Entrance fees",
      "5-star Nile Cruise accommodation",
      "Meals as specified",
    ],
    excluded: ["Egypt visa", "Cairo hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "epic-8-day-egypt-escapade",
    title: "Epic 8-Day Egypt Escapade",
    tagline: "Pyramids, temples, desert, and Red Sea — Egypt's greatest hits.",
    category: "multi-day",
    travelStyle: ["Adventure", "Private"],
    duration: "8 days",
    lengthDays: 8,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Red Sea"],
    rating: null,
    imageLabel: "Egypt Escapade",
    imageTone: "desert",
    description:
      "A fast-paced, highlight-packed week across Egypt's icons — the Pyramids, Luxor's temples and tombs, and a few days of Red Sea relaxation to close out the trip.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Luxor's East & West Banks",
      "Red Sea relaxation days",
      "Professional photoshoot",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Entrance fees",
      "Lunch on touring days",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "2-day-luxor-tour",
    title: "2 Days in Luxor: Karnak, Valley of the Kings & Hatshepsut",
    tagline: "The East Bank and West Bank of ancient Thebes, at an unhurried pace.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "2 days",
    lengthDays: 2,
    cities: 1,
    destinations: ["Luxor"],
    rating: null,
    imageLabel: "Luxor Temple",
    imageTone: "luxor",
    description:
      "Luxor deserves more than a rushed day trip. Two full days split cleanly across the Nile — Karnak and Luxor Temple on the East Bank, the Valley of the Kings and Hatshepsut's temple on the West Bank — with a private Egyptologist throughout and an optional sunrise hot-air balloon to open the second day.",
    highlights: [
      "Karnak Temple & the Great Hypostyle Hall",
      "Luxor Temple, seen in late afternoon light",
      "Valley of the Kings",
      "Temple of Hatshepsut at Deir el-Bahari",
      "Colossi of Memnon",
      "Optional sunrise hot-air balloon over the West Bank",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch both days",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Hot-air balloon (optional add-on)", "Tips", "Personal spending"],
    itinerary: [
      {
        day: 1,
        title: "East Bank",
        description: "Karnak Temple in the cooler morning hours, then Luxor Temple later in the day as the light softens.",
      },
      {
        day: 2,
        title: "West Bank",
        description: "Valley of the Kings, the Temple of Hatshepsut, and the Colossi of Memnon — with an optional sunrise balloon flight to start the day.",
      },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "aswan-abu-simbel-tour",
    title: "Aswan & Abu Simbel: Nubia's Ancient Temples",
    tagline: "Philae Temple, the High Dam, and the colossal statues of Abu Simbel.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "2 days",
    lengthDays: 2,
    cities: 1,
    destinations: ["Aswan", "Abu Simbel"],
    rating: null,
    imageLabel: "Abu Simbel",
    imageTone: "nile",
    description:
      "Aswan is Egypt at its most Nubian — a slower, greener city built around the Nile's First Cataract. Two days cover Philae Temple, the High Dam, and a felucca ride around Elephantine Island, followed by an early-morning drive south to Abu Simbel, where Ramesses II's colossal facade still faces the sunrise.",
    highlights: [
      "Philae Temple, dedicated to the goddess Isis",
      "Aswan High Dam & the Unfinished Obelisk",
      "Felucca sail around Elephantine Island",
      "Abu Simbel's Great and Small Temples",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch both days",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    itinerary: [
      {
        day: 1,
        title: "Aswan",
        description: "Philae Temple, the High Dam, the Unfinished Obelisk, and a late-afternoon felucca sail on the Nile.",
      },
      {
        day: 2,
        title: "Abu Simbel",
        description: "An early departure (roughly 4:30–5:00am) for the three-hour drive south, arriving at Abu Simbel's temples before the midday heat and the tour-bus crowds.",
      },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "alexandria-day-trip",
    title: "Alexandria Day Trip: Egypt's Mediterranean Capital",
    tagline: "Qaitbay Citadel, the Bibliotheca Alexandrina, and Egypt's Mediterranean coast.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural", "Family"],
    duration: "1 day / 12 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Alexandria"],
    rating: null,
    imageLabel: "Alexandria Coast",
    imageTone: "redsea",
    description:
      "A full day on Egypt's Mediterranean coast, roughly a two-and-a-half-hour drive from Cairo — the Citadel of Qaitbay, built on the site of the ancient Lighthouse, the modern Bibliotheca Alexandrina, Pompey's Pillar, and the Catacombs of Kom el Shoqafa, Alexandria's largest Roman-era cemetery.",
    highlights: [
      "Citadel of Qaitbay",
      "Bibliotheca Alexandrina",
      "Pompey's Pillar",
      "Catacombs of Kom el Shoqafa",
    ],
    included: [
      "Hotel pickup and return (from Cairo)",
      "Private air-conditioned vehicle",
      "Private English-speaking guide",
      "Entrance fees",
      "Lunch",
      "Bottled water",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "hurghada-red-sea-diving-snorkeling",
    title: "Hurghada Red Sea Snorkeling & Diving Day",
    tagline: "A full day on the water, over some of the clearest reefs in the Red Sea.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Hurghada", "Red Sea"],
    rating: null,
    imageLabel: "Red Sea Reef",
    imageTone: "redsea",
    description:
      "A boat day out of Hurghada, anchoring at two or three reef sites around the Giftun Islands and Orange Bay — snorkeling over coral gardens with a real chance of turtles and rays, plus an introductory dive for certified or first-time divers, with lunch served on board.",
    highlights: [
      "Giftun Islands & Orange Bay reef stops",
      "Snorkeling over coral gardens",
      "Optional introductory or certified diving",
      "Lunch served on board",
    ],
    included: [
      "Hotel pickup and return (Hurghada)",
      "Boat trip with snorkeling equipment",
      "Lunch and soft drinks on board",
      "Marine park entrance fees",
    ],
    excluded: ["Diving certification course", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "white-desert-safari-bahariya",
    title: "White Desert Safari: Bahariya Oasis & the Black Desert",
    tagline: "Wind-carved white rock formations, and a night camping under the stars.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "2 days / 1 night",
    lengthDays: 2,
    cities: 1,
    destinations: ["Bahariya Oasis", "White Desert"],
    rating: null,
    imageLabel: "White Desert",
    imageTone: "desert",
    description:
      "A 4x4 safari deep into Egypt's Western Desert — the volcanic hills of the Black Desert, Crystal Mountain's quartz-covered slopes, the sculpted formations of Agabat Valley, and a night camping in the White Desert itself, where wind-carved chalk formations turn gold and then silver as the sun sets and the stars come out.",
    highlights: [
      "Black Desert's volcanic hills",
      "Crystal Mountain",
      "Agabat Valley",
      "White Desert camping under the stars",
      "Bedouin-style dinner",
    ],
    included: [
      "Private air-conditioned transport to/from Bahariya",
      "4x4 vehicle for all desert transport",
      "Private guide",
      "Camping equipment",
      "Meals as specified",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Flights", "Tips", "Personal spending"],
    itinerary: [
      {
        day: 1,
        title: "Bahariya to the Black Desert",
        description: "Drive to Bahariya Oasis, then into the desert to see the Black Desert's volcanic hills and Crystal Mountain before making camp in the White Desert at sunset.",
      },
      {
        day: 2,
        title: "White Desert & Agabat Valley",
        description: "Sunrise over the White Desert's chalk formations, a walk through Agabat Valley, then the drive back to Cairo.",
      },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "mount-sinai-sunrise-hike",
    title: "Mount Sinai Sunrise Hike & St. Catherine's Monastery",
    tagline: "An overnight climb to watch the sun rise from the summit of Mount Sinai.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure"],
    duration: "1 day (overnight hike)",
    lengthDays: 1,
    cities: 1,
    destinations: ["Sinai", "St. Catherine"],
    rating: null,
    imageLabel: "Mount Sinai",
    imageTone: "desert",
    description:
      "An overnight excursion built around one moment: sunrise from the 2,285-meter summit of Mount Sinai. The guided ascent begins around 2am and takes roughly two and a half hours on foot (a camel is available for most of the route, for an additional cost); after sunrise and the descent, the trip continues to the 6th-century St. Catherine's Monastery, a UNESCO World Heritage Site built around the traditional site of the Burning Bush.",
    highlights: [
      "Sunrise from the summit of Mount Sinai",
      "Guided overnight ascent (camel option available)",
      "St. Catherine's Monastery, a UNESCO World Heritage Site",
      "The Chapel of the Burning Bush",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned transport",
      "Private guide",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Camel ride up the mountain (optional add-on)", "Warm clothing for the summit", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "memphis-saqqara-dahshur-tour",
    title: "Memphis, Saqqara & Dahshur: Egypt's Forgotten Pyramids",
    tagline: "The Step Pyramid, the Bent Pyramid, and Egypt's first capital — without the Giza crowds.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural"],
    duration: "1 day / 8 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Saqqara", "Dahshur", "Memphis"],
    rating: null,
    imageLabel: "Step Pyramid of Djoser",
    imageTone: "giza",
    description:
      "Before Giza, there was Saqqara — the Step Pyramid of Djoser, built around 2630 BCE, is the world's oldest major stone structure. This day pairs it with Dahshur's Bent and Red Pyramids, built a generation earlier as the architects worked out how to build a true pyramid, and Memphis, ancient Egypt's first capital, now an open-air museum.",
    highlights: [
      "Step Pyramid of Djoser, Saqqara",
      "Bent Pyramid & Red Pyramid, Dahshur",
      "Memphis Open-Air Museum",
      "Far fewer visitors than Giza",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Lunch", "Egypt visa", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "islamic-coptic-cairo-walking-tour",
    title: "Islamic Cairo & Coptic Cairo Walking Tour",
    tagline: "Al-Azhar Mosque, the Hanging Church, and the old city on foot.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural"],
    duration: "1 day / 7 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Cairo"],
    rating: null,
    imageLabel: "Khan el-Khalili",
    imageTone: "giza",
    description:
      "Cairo's oldest layers, on foot rather than from a car window — Al-Azhar Mosque and the medieval alleys of Islamic Cairo in the morning, then the walled Coptic Cairo quarter in the afternoon, including the Hanging Church and the Ben Ezra Synagogue, before finishing at Khan el-Khalili as the bazaar comes alive in the evening.",
    highlights: [
      "Al-Azhar Mosque",
      "Coptic Cairo: the Hanging Church & Ben Ezra Synagogue",
      "Khan el-Khalili bazaar",
      "Entirely on foot through the old city",
    ],
    included: [
      "Hotel pickup and return",
      "Private English-speaking guide",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Lunch", "Shopping", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "cairo-nile-dinner-cruise-night-tour",
    title: "Cairo by Night: Nile Dinner Cruise & City Lights",
    tagline: "Cairo's skyline from the water, with dinner and live entertainment on board.",
    category: "one-day",
    featured: false,
    travelStyle: ["Family", "Honeymoon"],
    duration: "Evening / 3 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Cairo"],
    rating: null,
    imageLabel: "Nile at Night",
    imageTone: "nile",
    description:
      "A slower way to see Cairo's other side — a dinner cruise along the Nile with the city's bridges and skyline lit up around you, a set Egyptian menu, and live music or a Tanoura folk dance show on board, depending on the evening.",
    highlights: [
      "Nile cruise through central Cairo",
      "Set dinner menu on board",
      "Live music / Tanoura show",
      "Cairo's skyline and bridges at night",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned transport",
      "Dinner cruise ticket",
      "Set menu dinner",
    ],
    excluded: ["Drinks beyond the set menu", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "luxor-east-bank-day-tour",
    title: "Luxor East Bank Day Tour: Karnak & Luxor Temple",
    tagline: "The living side of ancient Thebes, in a single unhurried day.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Luxor"],
    rating: null,
    imageLabel: "Karnak Temple",
    imageTone: "luxor",
    description:
      "For travelers who only have one day in Luxor and want the East Bank done properly rather than rushed — Karnak's Great Hypostyle Hall in the cooler morning hours, then Luxor Temple later in the day, once the light and the temperature have both softened.",
    highlights: [
      "Karnak Temple & the Great Hypostyle Hall",
      "Avenue of Sphinxes",
      "Luxor Temple in late-afternoon light",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "luxor-west-bank-day-tour",
    title: "Luxor West Bank Day Tour: Valley of the Kings & Hatshepsut",
    tagline: "The Valley of the Kings, Hatshepsut's temple, and the Colossi of Memnon in one day.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Luxor"],
    rating: null,
    imageLabel: "Valley of the Kings",
    imageTone: "luxor",
    description:
      "The West Bank on its own, at the pace it deserves — an early start into the Valley of the Kings before the heat builds, the Temple of Hatshepsut carved into the cliffs at Deir el-Bahari, and the Colossi of Memnon on the way back.",
    highlights: [
      "Valley of the Kings",
      "Temple of Hatshepsut, Deir el-Bahari",
      "Colossi of Memnon",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Lunch", "Tombs requiring a separate ticket", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "dendera-abydos-day-tour",
    title: "Dendera & Abydos: The Temples Beyond Luxor",
    tagline: "Two of Egypt's best-preserved temples, both usually skipped by shorter trips.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural"],
    duration: "1 day / 10 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Dendera", "Abydos"],
    rating: null,
    imageLabel: "Dendera Temple",
    imageTone: "luxor",
    description:
      "A long day by car north of Luxor, and one most travelers who take it call worth every hour — the Temple of Hathor at Dendera, with its famous zodiac ceiling and colors still vivid after two thousand years, and the Temple of Seti I at Abydos, where the wall reliefs are among the best-preserved in Egypt.",
    highlights: [
      "Temple of Hathor, Dendera, and its zodiac ceiling",
      "Temple of Seti I, Abydos",
      "Some of the best-preserved reliefs in Egypt",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "edfu-kom-ombo-day-tour",
    title: "Edfu & Kom Ombo Temples Day Tour",
    tagline: "The best-preserved temple in Egypt, and one built for two gods at once.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Edfu", "Kom Ombo"],
    rating: null,
    imageLabel: "Temple of Horus, Edfu",
    imageTone: "nile",
    description:
      "Between Luxor and Aswan sit two temples most travelers only glimpse from a passing Nile cruise ship — the Temple of Horus at Edfu, the most completely preserved temple in Egypt, and the unusual double temple at Kom Ombo, dedicated equally to the crocodile god Sobek and the falcon god Horus.",
    highlights: [
      "Temple of Horus, Edfu — Egypt's best-preserved temple",
      "Kom Ombo's double temple to Sobek and Horus",
      "Crocodile Museum, Kom Ombo",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "4-day-nile-cruise-luxor-aswan",
    title: "4-Day Nile Cruise: Luxor to Aswan",
    tagline: "A dedicated Nile cruise, without a Cairo itinerary built around it.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "4 days / 3 nights",
    lengthDays: 4,
    cities: 2,
    destinations: ["Luxor", "Aswan"],
    rating: null,
    imageLabel: "Nile Cruise Ship",
    imageTone: "nile",
    description:
      "For travelers who already have Cairo covered, or who are flying directly into Luxor — a 5-star Nile cruise ship sailing from Luxor to Aswan, with shore excursions to Karnak, Luxor Temple, the Valley of the Kings, Edfu, Kom Ombo, and Philae Temple built into the itinerary.",
    highlights: [
      "5-star Nile Cruise, Luxor to Aswan",
      "Karnak, Luxor Temple & the Valley of the Kings",
      "Edfu & Kom Ombo temples en route",
      "Philae Temple, Aswan",
    ],
    included: [
      "5-star Nile Cruise cabin accommodation",
      "Meals aboard the cruise",
      "All shore excursions with a private Egyptologist",
      "Entrance fees",
    ],
    excluded: ["Flights to/from Luxor or Aswan", "Egypt visa", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "7-night-nile-cruise-luxor-aswan",
    title: "7-Night Nile Cruise: Luxor to Aswan",
    tagline: "The unhurried version — a full week on the water between Luxor and Aswan.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Luxury", "Slow Travel"],
    duration: "8 days / 7 nights",
    lengthDays: 8,
    cities: 2,
    destinations: ["Luxor", "Aswan"],
    rating: null,
    imageLabel: "Nile Cruise Deck",
    imageTone: "nile",
    description:
      "The same Luxor-to-Aswan route as our standard cruise, stretched over a full week rather than a few days — time to actually sit on deck and watch the Nile Valley pass by between stops, with the same temples covered at a genuinely slow pace instead of a packed schedule.",
    highlights: [
      "A full week aboard, Luxor to Aswan",
      "Every major temple on the route, unhurried",
      "Extended time on deck between stops",
    ],
    included: [
      "5-star Nile Cruise cabin accommodation",
      "Meals aboard the cruise",
      "All shore excursions with a private Egyptologist",
      "Entrance fees",
    ],
    excluded: ["Flights to/from Luxor or Aswan", "Egypt visa", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "aswan-nubian-village-philae-tour",
    title: "Aswan Nubian Village & Philae Temple Day Tour",
    tagline: "A felucca to a Nubian village, and Philae Temple on its island in the Nile.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural", "Family"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Aswan"],
    rating: null,
    imageLabel: "Nubian Village, Aswan",
    imageTone: "nile",
    description:
      "A shorter, gentler introduction to Aswan for travelers not doing the full Abu Simbel trip — a felucca sail to a colorful Nubian village on the Nile, and Philae Temple, relocated stone by stone to Agilkia Island when the High Dam was built.",
    highlights: [
      "Felucca sail to a Nubian village",
      "Philae Temple, dedicated to the goddess Isis",
      "Traditional Nubian tea and hospitality",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Felucca sail",
      "Private English-speaking guide",
      "Entrance fees",
    ],
    excluded: ["Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "kalabsha-temple-nubian-museum-tour",
    title: "Kalabsha Temple & Nubian Museum Tour",
    tagline: "A relocated temple, and the museum that tells Nubia's story.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural"],
    duration: "Half day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Aswan"],
    rating: null,
    imageLabel: "Nubian Museum",
    imageTone: "nile",
    description:
      "Kalabsha Temple, moved to an island near the High Dam to save it from Lake Nasser's rising water, paired with the Nubian Museum — the single best place in Egypt to understand Nubian history and culture, and what was lost and preserved when the High Dam was built.",
    highlights: [
      "Kalabsha Temple, relocated by the High Dam",
      "Nubian Museum",
      "Aswan High Dam viewpoint",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking guide",
      "Entrance fees",
    ],
    excluded: ["Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "ras-mohammed-snorkeling-tour",
    title: "Sharm El Sheikh: Ras Mohammed National Park Snorkeling",
    tagline: "One of the Red Sea's most protected reefs, by boat from Sharm El Sheikh.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure", "Family"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Sharm El Sheikh", "Red Sea"],
    rating: null,
    imageLabel: "Ras Mohammed Reef",
    imageTone: "redsea",
    description:
      "A full day out of Sharm El Sheikh at Ras Mohammed National Park, one of the Red Sea's most protected marine reserves — multiple snorkeling stops over coral gardens, a chance to see the park's Magic Lake, and lunch served on board between stops.",
    highlights: [
      "Ras Mohammed National Park reef stops",
      "Snorkeling over protected coral gardens",
      "Magic Lake",
      "Lunch served on board",
    ],
    included: [
      "Hotel pickup and return",
      "Boat trip with snorkeling equipment",
      "Lunch on board",
      "Marine park entrance fees",
    ],
    excluded: ["Diving (available as an add-on)", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "dahab-blue-hole-three-pools-tour",
    title: "Dahab: Blue Hole & Three Pools Diving Day",
    tagline: "A legendary sinkhole dive site, and a calmer snorkel among coral towers.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Dahab", "Sinai"],
    rating: null,
    imageLabel: "Blue Hole, Dahab",
    imageTone: "redsea",
    description:
      "Dahab's Blue Hole — a submarine sinkhole dropping well over 100 meters, ringed with coral and famous among divers worldwide — paired with the calmer Three Pools nearby, three sandy-floored pools among coral towers that make for some of the easiest, most rewarding snorkeling in Sinai.",
    highlights: [
      "The Blue Hole",
      "Three Pools snorkeling",
      "Dahab's laid-back coastline",
    ],
    included: [
      "Hotel pickup and return",
      "Private transport",
      "Snorkeling equipment",
      "Local guide",
    ],
    excluded: ["Scuba diving certification/equipment (available separately)", "Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "colored-canyon-nuweiba-tour",
    title: "Colored Canyon & Nuweiba Desert Adventure",
    tagline: "A narrow, rainbow-striped canyon, and a Bedouin stretch of Sinai coast.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Nuweiba", "Sinai"],
    rating: null,
    imageLabel: "Colored Canyon, Sinai",
    imageTone: "desert",
    description:
      "A jeep safari into the Colored Canyon, a narrow sandstone gorge striped in reds, purples, and yellows from mineral deposits in the rock, followed by time on Nuweiba's quieter Bedouin-run coastline — a genuinely different side of Sinai from its resort towns.",
    highlights: [
      "Colored Canyon hike",
      "4x4 desert crossing",
      "Nuweiba's Bedouin coastline",
    ],
    included: [
      "Hotel pickup and return",
      "4x4 desert transport",
      "Local Bedouin guide",
      "Bottled water",
    ],
    excluded: ["Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "el-gouna-lagoon-day",
    title: "El Gouna: Lagoon & Red Sea Beach Day",
    tagline: "A designed lagoon town on the Red Sea, built around the water.",
    category: "one-day",
    featured: false,
    travelStyle: ["Slow Travel", "Honeymoon"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["El Gouna", "Red Sea"],
    rating: null,
    imageLabel: "El Gouna Lagoon",
    imageTone: "redsea",
    description:
      "El Gouna is unlike anywhere else on the Red Sea coast — a purpose-built town of lagoons and small islands connected by bridges, known internationally as a kitesurfing destination and, closer to home, simply for having some of the calmest turquoise water on the coast. A day here is built around the lagoon itself: a boat out to the reef, and time to just be on the water.",
    highlights: [
      "El Gouna's lagoons and marina",
      "Reef boat trip",
      "Optional kitesurfing or watersports",
    ],
    included: [
      "Hotel pickup and return",
      "Private transport",
      "Lagoon boat trip",
    ],
    excluded: ["Watersports equipment rental", "Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "marsa-alam-dolphin-house-tour",
    title: "Marsa Alam: Dolphin House Snorkeling at Sataya Reef",
    tagline: "Snorkeling alongside wild spinner dolphins in their own sheltered lagoon.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure", "Honeymoon"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Marsa Alam", "Red Sea"],
    rating: null,
    imageLabel: "Sataya Reef",
    imageTone: "redsea",
    description:
      "Sataya Reef, better known as Dolphin House, is a shallow, sheltered lagoon south of Marsa Alam where pods of wild spinner dolphins regularly rest and feed — genuinely wild animals in their own habitat, not a marine park. It's roughly a two-hour boat journey each way, and there's no guarantee of dolphins on any given day, but the reef itself and the chance are what make the trip.",
    highlights: [
      "Sataya Reef (Dolphin House)",
      "Snorkeling with wild spinner dolphins (not guaranteed)",
      "Reef snorkeling with turtles, rays, and reef fish",
    ],
    included: [
      "Hotel pickup and return",
      "Boat trip with snorkeling equipment",
      "Lunch on board",
    ],
    excluded: ["Diving (available as an add-on)", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "soma-bay-watersports-relaxation",
    title: "Soma Bay: Red Sea Watersports & Relaxation",
    tagline: "A quieter Red Sea peninsula, built for a slower kind of beach day.",
    category: "one-day",
    featured: false,
    travelStyle: ["Slow Travel", "Honeymoon"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Soma Bay", "Red Sea"],
    rating: null,
    imageLabel: "Soma Bay",
    imageTone: "redsea",
    description:
      "Soma Bay sits on its own peninsula south of Hurghada, with fewer crowds and calmer water than the busier resort strips nearby — a day built around the beach itself, with windsurfing, kitesurfing, or diving available for travelers who want to add activity to the relaxation.",
    highlights: [
      "Private beach access",
      "Calm, sheltered water",
      "Optional windsurfing, kitesurfing, or diving",
    ],
    included: [
      "Hotel pickup and return",
      "Private transport",
      "Beach access",
    ],
    excluded: ["Watersports equipment/lessons", "Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "wadi-el-hitan-whale-valley-safari",
    title: "Whale Valley Fossil Safari: Wadi El Hitan",
    tagline: "40-million-year-old whale skeletons, in the middle of the Egyptian desert.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure", "Family"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Fayoum", "Wadi El Hitan"],
    rating: null,
    imageLabel: "Wadi El Hitan Fossils",
    imageTone: "desert",
    description:
      "Wadi El Hitan — the Valley of the Whales — is Egypt's first UNESCO natural World Heritage site, and it earned that status for something genuinely strange: the fossilized skeletons of some of the earliest whales, animals still carrying the vestigial legs of their land-dwelling ancestors, scattered across open desert 40 million years after they died. A small fossil museum on site explains what you're looking at before you walk out among the skeletons themselves.",
    highlights: [
      "Fossilized whale skeletons in situ",
      "Wadi El Hitan Fossil & Climate Change Museum",
      "Egypt's first UNESCO natural World Heritage Site",
    ],
    included: [
      "Hotel pickup and return",
      "Private 4x4 vehicle",
      "Private guide",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Lunch", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "dakhla-kharga-oasis-circuit",
    title: "Western Desert Oases Circuit: Dakhla & Kharga",
    tagline: "A multi-day desert loop through two of Egypt's least-visited oases.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "4 days / 3 nights",
    lengthDays: 4,
    cities: 2,
    destinations: ["Dakhla Oasis", "Kharga Oasis"],
    rating: null,
    imageLabel: "Dakhla Oasis",
    imageTone: "desert",
    description:
      "A genuine expedition rather than a day trip — Dakhla Oasis, roughly 740km southwest of Cairo, holds the medieval mudbrick town of Al-Qasr, the Deir al-Hagar temple, and hot springs among its palm groves; Kharga, on the return route, adds the Necropolis of al-Bagawat, one of the earliest and best-preserved Christian cemeteries anywhere. Best traveled October through March, when desert daytime temperatures stay comfortable.",
    highlights: [
      "Al-Qasr's medieval mudbrick old town, Dakhla",
      "Deir al-Hagar Temple",
      "Necropolis of al-Bagawat, Kharga",
      "Hot springs among the palm groves",
    ],
    included: [
      "Private 4x4 transport throughout",
      "Private guide",
      "Accommodation as arranged",
      "Entrance fees",
    ],
    excluded: ["Egypt visa", "Flights", "Some meals", "Tips", "Personal spending"],
    itinerary: [
      { day: 1, title: "Cairo to Dakhla", description: "The long desert drive south, arriving in Dakhla by evening." },
      { day: 2, title: "Dakhla Oasis", description: "Al-Qasr's old town, the Deir al-Hagar temple, and the oasis's hot springs." },
      { day: 3, title: "Dakhla to Kharga", description: "Drive to Kharga Oasis, visiting the Necropolis of al-Bagawat along the way." },
      { day: 4, title: "Kharga to Luxor or Cairo", description: "Final desert stretch, connecting back to the Nile Valley." },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "lake-nasser-cruise-aswan-abu-simbel",
    title: "Lake Nasser Cruise: Aswan to Abu Simbel by Water",
    tagline: "A small-ship cruise across Lake Nasser, ending at Abu Simbel's temples.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Luxury", "Slow Travel"],
    duration: "4 days / 3 nights",
    lengthDays: 4,
    cities: 2,
    destinations: ["Aswan", "Lake Nasser", "Abu Simbel"],
    rating: null,
    imageLabel: "Lake Nasser",
    imageTone: "nile",
    description:
      "Instead of a road trip to Abu Simbel, a small-ship cruise across Lake Nasser itself — the vast reservoir created by the Aswan High Dam — stopping at temples that were also relocated to its shores, including Wadi es-Sebua and Amada, before arriving at Abu Simbel by water and seeing Ramesses II's colossal facade the way most visitors never do.",
    highlights: [
      "Lake Nasser by small ship",
      "Wadi es-Sebua & Amada temples",
      "Arriving at Abu Simbel by water",
      "Far fewer visitors than the road-trip route",
    ],
    included: [
      "Cabin accommodation aboard the Lake Nasser ship",
      "Meals aboard",
      "All shore excursions with a private Egyptologist",
      "Entrance fees",
    ],
    excluded: ["Transport to/from Aswan", "Egypt visa", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
];

export function getTourBySlug(slug: string) {
  return tours.find((t) => t.slug === slug);
}
