import type { Tour } from "./types";

// Popular Tours — edit durations, ratings, itineraries, and pricing here.
// price.amount = null means "Contact for pricing" (shown as "Get a Quote").

export const tours: Tour[] = [
  {
    slug: "1-day-giza-tour",
    title: "1 Day Giza Tour: Exploring Ancient Wonders",
    tagline: "Pyramids, Sphinx, and a free private photoshoot — all in one day.",
    category: "one-day",
    featured: true,
    travelStyle: ["Cultural", "Family"],
    duration: "8 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Giza"],
    rating: { score: 4.98, count: 8 },
    badge: "Free Private Photoshoot",
    imageLabel: "Giza Pyramids",
    imageTone: "giza",
    description:
      "Our signature day trip combines the Giza Pyramids, the Great Sphinx, and the Valley Temple with a camel ride, the iconic Nine Pyramids View, and a complimentary professional photoshoot — finished off with an Egyptian lunch and a perfume and essential oils experience.",
    highlights: [
      "Giza Pyramids & Great Sphinx",
      "Valley Temple",
      "Camel experience",
      "Nine Pyramids View",
      "Complimentary professional photoshoot",
      "Egyptian lunch",
      "Perfume & essential oils experience",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Professional content creator",
      "Entrance fees",
      "Lunch",
      "Bottled water",
      "Shopping tours",
      "Taxes and service charges",
    ],
    excluded: ["Extras not mentioned", "Tips", "Hotels", "Flights"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "fayoum-nature-tour",
    title: "Fayoum: The Beautiful Nature of Egypt",
    tagline: "Waterfalls, desert lakes, and Egypt's quieter, greener side.",
    category: "one-day",
    travelStyle: ["Slow Travel", "Adventure"],
    duration: "1 day / 12 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Fayoum"],
    rating: null,
    imageLabel: "Fayoum Oasis",
    imageTone: "desert",
    description:
      "Escape the city for Fayoum's dramatic landscapes — Wadi El Rayan's waterfalls, golden dunes, and the Magic Lake — a favorite for travelers who want Egypt's natural beauty alongside its ancient history.",
    highlights: [
      "Wadi El Rayan waterfalls",
      "Magic Lake",
      "Desert scenery & sand dunes",
      "Private Egyptologist guide",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking guide",
      "Lunch",
      "Bottled water",
      "Entrance fees",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Optional activities"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "red-sea-relaxation",
    title: "Egypt's Relaxation Mood: Red Sea",
    tagline: "Turquoise water, white sand, and nothing on the agenda.",
    category: "one-day",
    featured: true,
    travelStyle: ["Slow Travel", "Honeymoon"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Red Sea"],
    rating: null,
    imageLabel: "Red Sea Coast",
    imageTone: "redsea",
    description:
      "A slower-paced day built around the Red Sea's calm, clear water — swimming, snorkeling, and lounging on a private beach, with the option to add our Luxe Yacht experience.",
    highlights: [
      "Private beach access",
      "Swimming & snorkeling",
      "Optional Red Sea Luxe Yacht add-on",
      "Private transportation",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Bottled water",
      "Beach access",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Water sports equipment rental"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "3-day-cairo-giza",
    title: "Three-Day Excursion: Cairo & Giza",
    tagline: "A complete first taste of Egypt's ancient and modern capital.",
    category: "multi-day",
    travelStyle: ["Cultural", "Family"],
    duration: "3 days",
    lengthDays: 3,
    cities: 1,
    destinations: ["Cairo", "Giza"],
    rating: null,
    imageLabel: "Cairo & Giza",
    imageTone: "giza",
    description:
      "Three unhurried days across Cairo and Giza — pyramids, museums, Islamic and Coptic Cairo, and the bazaars of Khan el-Khalili — with a private Egyptologist throughout.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Grand Egyptian Museum / Egyptian Museum",
      "Coptic Cairo & Khan el-Khalili",
      "Professional photoshoot",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch daily",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "siwa-oasis",
    title: "Desert Dreams: Siwa Oasis",
    tagline: "Egypt's most remote oasis — salt lakes, dunes, and starlit skies.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "3 days",
    lengthDays: 3,
    cities: 1,
    destinations: ["Siwa Oasis"],
    rating: null,
    imageLabel: "Siwa Oasis",
    imageTone: "desert",
    description:
      "A journey deep into the Great Sand Sea to Siwa — natural springs, salt lakes, the Oracle Temple, and some of the darkest, clearest night skies in Egypt.",
    highlights: [
      "Great Sand Sea",
      "Salt lakes & natural springs",
      "Oracle Temple",
      "ATV & 4x4 desert safari",
    ],
    included: [
      "Private air-conditioned transfers",
      "Private English-speaking guide",
      "Entrance fees",
      "Accommodation as arranged",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "3-days-jordan",
    title: "3 Days Exploring the Wonders of Jordan",
    tagline: "Wadi Rum, Petra, and the Dead Sea in a single private itinerary.",
    category: "jordan",
    featured: true,
    travelStyle: ["Adventure", "Cultural", "Private"],
    duration: "3 days",
    lengthDays: 3,
    cities: 3,
    destinations: ["Wadi Rum", "Petra", "Dead Sea"],
    rating: null,
    imageLabel: "Petra, Jordan",
    imageTone: "jordan",
    description:
      "From the rose-red city of Petra to a 4x4 Jeep safari through Wadi Rum's Martian landscape, finishing with a float in the Dead Sea — Jordan's essential highlights, privately guided.",
    highlights: [
      "Petra — the Treasury & Siq",
      "Wadi Rum 4x4 Jeep safari",
      "Dead Sea floating experience",
      "Airport meet & greet",
    ],
    included: [
      "Airport meet & greet",
      "Guest relations assistance",
      "Private air-conditioned transfers",
      "English-speaking guide",
      "4x4 Jeep Safari",
      "Entrance tickets",
    ],
    excluded: [
      "Flights",
      "Hotels",
      "Egypt visa",
      "Optional tours",
      "Personal expenses",
      "Tips",
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "5-day-giza-cairo-alexandria",
    title: "5-Day Egypt: Giza, Cairo & Alexandria",
    tagline: "Pyramids, the capital, and the Mediterranean coast.",
    category: "multi-day",
    travelStyle: ["Cultural"],
    duration: "5 days",
    lengthDays: 5,
    cities: 2,
    destinations: ["Cairo", "Giza", "Alexandria"],
    rating: { score: 5, count: 1 },
    imageLabel: "Alexandria Coast",
    imageTone: "nile",
    description:
      "Combine Cairo and Giza's ancient highlights with a day trip to Alexandria's Mediterranean charm — the Citadel of Qaitbay, Bibliotheca Alexandrina, and the Catacombs of Kom el Shoqafa.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Egyptian Museum",
      "Citadel of Qaitbay",
      "Bibliotheca Alexandrina",
      "Professional photoshoot",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch daily",
      "Professional photoshoot",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "6-day-cairo-giza-luxor",
    title: "6 Days: Cairo, Giza & Luxor",
    tagline: "Pyramids, temples, and the Valley of the Kings.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Cultural", "Private"],
    duration: "6 days",
    lengthDays: 6,
    cities: 3,
    destinations: ["Cairo", "Giza", "Luxor"],
    rating: { score: 4.95, count: 8 },
    imageLabel: "Luxor Temple",
    imageTone: "luxor",
    description:
      "Six days across Cairo, Giza, and Luxor — the Nine Pyramids photoshoot, Coptic Cairo, Khan el-Khalili, and the temples and tombs of ancient Thebes on both banks of the Nile.",
    highlights: [
      "Nine Pyramids professional photoshoot",
      "Coptic Cairo & Khan el-Khalili",
      "Avenue of Sphinxes & Karnak Temple",
      "Valley of the Kings & Hatshepsut Temple",
      "Optional hot-air balloon over Luxor",
    ],
    included: [
      "Nine Pyramids professional photoshoot",
      "Professional content creator",
      "Sightseeing transportation",
      "Lunch",
      "Camel ride",
      "English-speaking tour manager",
      "Entrance fees",
    ],
    excluded: [
      "Egypt visa",
      "Hotels",
      "Flights",
      "Personal spending",
      "Optional activities",
      "Tips",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Cairo", description: "Meet and greet, transfer, and welcome briefing." },
      {
        day: 2,
        title: "Giza",
        description:
          "Giza Pyramids, Sphinx, Valley Temple, professional photoshoot, lunch, and a perfume & essential oils experience.",
      },
      {
        day: 3,
        title: "Cairo",
        description:
          "Coptic Cairo, the Hanging Church, the National Museum of Egyptian Civilization, Royal Mummies, and Khan el-Khalili bazaar.",
      },
      {
        day: 4,
        title: "Luxor — East Bank",
        description: "Avenue of Sphinxes, Karnak Temple complex, and Luxor Temple.",
      },
      {
        day: 5,
        title: "Luxor — West Bank",
        description:
          "Optional hot-air balloon at sunrise, Valley of the Kings, Hatshepsut Temple, an alabaster and marble workshop, and the Colossi of Memnon.",
      },
      { day: 6, title: "Departure", description: "Transfer to the airport for your onward flight." },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "8-day-essential-egypt-nile-cruise",
    title: "8 Days Essential Egypt + 5-Day Nile Cruise",
    tagline: "Cairo and Giza, then five days cruising the Nile in 5-star comfort.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Private", "Cultural"],
    duration: "8 days",
    lengthDays: 8,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Aswan"],
    rating: { score: 5, count: 18 },
    imageLabel: "Nile Cruise",
    imageTone: "nile",
    description:
      "Our most complete Egypt itinerary — Cairo and Giza's ancient wonders followed by a 5-day Nile Cruise from Luxor to Aswan, visiting Karnak, the Valley of the Kings, Philae Temple, and the Aswan High Dam along the way.",
    highlights: [
      "Nine Pyramids professional photoshoot",
      "5-star Nile Cruise, Luxor to Aswan",
      "Karnak & Luxor Temples",
      "Valley of the Kings",
      "Philae Temple & the Unfinished Obelisk",
    ],
    included: [
      "Professional Nine Pyramids photoshoot",
      "Professional content creator",
      "Air-conditioned sightseeing transport",
      "Lunch",
      "Camel ride",
      "English-speaking tour manager",
      "Entrance fees",
      "5-star Nile Cruise accommodation",
      "Meals aboard the cruise",
    ],
    excluded: [
      "Egypt visa",
      "Cairo hotels",
      "Flights",
      "Personal spending",
      "Optional activities",
      "Tips",
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "10-day-private-luxurious-trip",
    title: "10-Day Private & Luxurious Trip",
    tagline: "The full country, at a private, unhurried, five-star pace.",
    category: "multi-day",
    featured: true,
    travelStyle: ["Luxury", "Private", "Honeymoon"],
    duration: "10 days",
    lengthDays: 10,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Aswan"],
    rating: { score: 3.67, count: 3 },
    badge: "Customizable",
    imageLabel: "Aswan Sunset",
    imageTone: "nile",
    description:
      "Ten fully private days combining Cairo and Giza, a Nile Cruise, and time built in for photoshoots, relaxation, and any experience you'd like to add — designed around your pace, not a fixed group schedule.",
    highlights: [
      "Fully private throughout",
      "Nine Pyramids photoshoot",
      "5-star Nile Cruise",
      "Flexible, customizable pacing",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Entrance fees",
      "5-star Nile Cruise accommodation",
      "Meals as specified",
    ],
    excluded: ["Egypt visa", "Cairo hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "epic-8-day-egypt-escapade",
    title: "Epic 8-Day Egypt Escapade",
    tagline: "Pyramids, temples, desert, and Red Sea — Egypt's greatest hits.",
    category: "multi-day",
    travelStyle: ["Adventure", "Private"],
    duration: "8 days",
    lengthDays: 8,
    cities: 4,
    destinations: ["Cairo", "Giza", "Luxor", "Red Sea"],
    rating: null,
    imageLabel: "Egypt Escapade",
    imageTone: "desert",
    description:
      "A fast-paced, highlight-packed week across Egypt's icons — the Pyramids, Luxor's temples and tombs, and a few days of Red Sea relaxation to close out the trip.",
    highlights: [
      "Giza Pyramids & Sphinx",
      "Luxor's East & West Banks",
      "Red Sea relaxation days",
      "Professional photoshoot",
    ],
    included: [
      "Private air-conditioned transportation",
      "Private English-speaking Egyptologist",
      "Professional photoshoot",
      "Entrance fees",
      "Lunch on touring days",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "2-day-luxor-tour",
    title: "2 Days in Luxor: Karnak, Valley of the Kings & Hatshepsut",
    tagline: "The East Bank and West Bank of ancient Thebes, at an unhurried pace.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "2 days",
    lengthDays: 2,
    cities: 1,
    destinations: ["Luxor"],
    rating: null,
    imageLabel: "Luxor Temple",
    imageTone: "luxor",
    description:
      "Luxor deserves more than a rushed day trip. Two full days split cleanly across the Nile — Karnak and Luxor Temple on the East Bank, the Valley of the Kings and Hatshepsut's temple on the West Bank — with a private Egyptologist throughout and an optional sunrise hot-air balloon to open the second day.",
    highlights: [
      "Karnak Temple & the Great Hypostyle Hall",
      "Luxor Temple, seen in late afternoon light",
      "Valley of the Kings",
      "Temple of Hatshepsut at Deir el-Bahari",
      "Colossi of Memnon",
      "Optional sunrise hot-air balloon over the West Bank",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch both days",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Hot-air balloon (optional add-on)", "Tips", "Personal spending"],
    itinerary: [
      {
        day: 1,
        title: "East Bank",
        description: "Karnak Temple in the cooler morning hours, then Luxor Temple later in the day as the light softens.",
      },
      {
        day: 2,
        title: "West Bank",
        description: "Valley of the Kings, the Temple of Hatshepsut, and the Colossi of Memnon — with an optional sunrise balloon flight to start the day.",
      },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "aswan-abu-simbel-tour",
    title: "Aswan & Abu Simbel: Nubia's Ancient Temples",
    tagline: "Philae Temple, the High Dam, and the colossal statues of Abu Simbel.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Cultural", "Private"],
    duration: "2 days",
    lengthDays: 2,
    cities: 1,
    destinations: ["Aswan", "Abu Simbel"],
    rating: null,
    imageLabel: "Abu Simbel",
    imageTone: "nile",
    description:
      "Aswan is Egypt at its most Nubian — a slower, greener city built around the Nile's First Cataract. Two days cover Philae Temple, the High Dam, and a felucca ride around Elephantine Island, followed by an early-morning drive south to Abu Simbel, where Ramesses II's colossal facade still faces the sunrise.",
    highlights: [
      "Philae Temple, dedicated to the goddess Isis",
      "Aswan High Dam & the Unfinished Obelisk",
      "Felucca sail around Elephantine Island",
      "Abu Simbel's Great and Small Temples",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned vehicle",
      "Private English-speaking Egyptologist",
      "Entrance fees",
      "Lunch both days",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Hotels", "Flights", "Tips", "Personal spending"],
    itinerary: [
      {
        day: 1,
        title: "Aswan",
        description: "Philae Temple, the High Dam, the Unfinished Obelisk, and a late-afternoon felucca sail on the Nile.",
      },
      {
        day: 2,
        title: "Abu Simbel",
        description: "An early departure (roughly 4:30–5:00am) for the three-hour drive south, arriving at Abu Simbel's temples before the midday heat and the tour-bus crowds.",
      },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "alexandria-day-trip",
    title: "Alexandria Day Trip: Egypt's Mediterranean Capital",
    tagline: "Qaitbay Citadel, the Bibliotheca Alexandrina, and Egypt's Mediterranean coast.",
    category: "one-day",
    featured: false,
    travelStyle: ["Cultural", "Family"],
    duration: "1 day / 12 hours",
    lengthDays: 1,
    cities: 1,
    destinations: ["Alexandria"],
    rating: null,
    imageLabel: "Alexandria Coast",
    imageTone: "redsea",
    description:
      "A full day on Egypt's Mediterranean coast, roughly a two-and-a-half-hour drive from Cairo — the Citadel of Qaitbay, built on the site of the ancient Lighthouse, the modern Bibliotheca Alexandrina, Pompey's Pillar, and the Catacombs of Kom el Shoqafa, Alexandria's largest Roman-era cemetery.",
    highlights: [
      "Citadel of Qaitbay",
      "Bibliotheca Alexandrina",
      "Pompey's Pillar",
      "Catacombs of Kom el Shoqafa",
    ],
    included: [
      "Hotel pickup and return (from Cairo)",
      "Private air-conditioned vehicle",
      "Private English-speaking guide",
      "Entrance fees",
      "Lunch",
      "Bottled water",
    ],
    excluded: ["Tips", "Hotels", "Flights", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "hurghada-red-sea-diving-snorkeling",
    title: "Hurghada Red Sea Snorkeling & Diving Day",
    tagline: "A full day on the water, over some of the clearest reefs in the Red Sea.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "1 day",
    lengthDays: 1,
    cities: 1,
    destinations: ["Hurghada", "Red Sea"],
    rating: null,
    imageLabel: "Red Sea Reef",
    imageTone: "redsea",
    description:
      "A boat day out of Hurghada, anchoring at two or three reef sites around the Giftun Islands and Orange Bay — snorkeling over coral gardens with a real chance of turtles and rays, plus an introductory dive for certified or first-time divers, with lunch served on board.",
    highlights: [
      "Giftun Islands & Orange Bay reef stops",
      "Snorkeling over coral gardens",
      "Optional introductory or certified diving",
      "Lunch served on board",
    ],
    included: [
      "Hotel pickup and return (Hurghada)",
      "Boat trip with snorkeling equipment",
      "Lunch and soft drinks on board",
      "Marine park entrance fees",
    ],
    excluded: ["Diving certification course", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "white-desert-safari-bahariya",
    title: "White Desert Safari: Bahariya Oasis & the Black Desert",
    tagline: "Wind-carved white rock formations, and a night camping under the stars.",
    category: "multi-day",
    featured: false,
    travelStyle: ["Adventure", "Slow Travel"],
    duration: "2 days / 1 night",
    lengthDays: 2,
    cities: 1,
    destinations: ["Bahariya Oasis", "White Desert"],
    rating: null,
    imageLabel: "White Desert",
    imageTone: "desert",
    description:
      "A 4x4 safari deep into Egypt's Western Desert — the volcanic hills of the Black Desert, Crystal Mountain's quartz-covered slopes, the sculpted formations of Agabat Valley, and a night camping in the White Desert itself, where wind-carved chalk formations turn gold and then silver as the sun sets and the stars come out.",
    highlights: [
      "Black Desert's volcanic hills",
      "Crystal Mountain",
      "Agabat Valley",
      "White Desert camping under the stars",
      "Bedouin-style dinner",
    ],
    included: [
      "Private air-conditioned transport to/from Bahariya",
      "4x4 vehicle for all desert transport",
      "Private guide",
      "Camping equipment",
      "Meals as specified",
      "Bottled water",
    ],
    excluded: ["Egypt visa", "Flights", "Tips", "Personal spending"],
    itinerary: [
      {
        day: 1,
        title: "Bahariya to the Black Desert",
        description: "Drive to Bahariya Oasis, then into the desert to see the Black Desert's volcanic hills and Crystal Mountain before making camp in the White Desert at sunset.",
      },
      {
        day: 2,
        title: "White Desert & Agabat Valley",
        description: "Sunrise over the White Desert's chalk formations, a walk through Agabat Valley, then the drive back to Cairo.",
      },
    ],
    price: { amount: null, note: "Ask us for today's rate" },
  },
  {
    slug: "mount-sinai-sunrise-hike",
    title: "Mount Sinai Sunrise Hike & St. Catherine's Monastery",
    tagline: "An overnight climb to watch the sun rise from the summit of Mount Sinai.",
    category: "one-day",
    featured: false,
    travelStyle: ["Adventure"],
    duration: "1 day (overnight hike)",
    lengthDays: 1,
    cities: 1,
    destinations: ["Sinai", "St. Catherine"],
    rating: null,
    imageLabel: "Mount Sinai",
    imageTone: "desert",
    description:
      "An overnight excursion built around one moment: sunrise from the 2,285-meter summit of Mount Sinai. The guided ascent begins around 2am and takes roughly two and a half hours on foot (a camel is available for most of the route, for an additional cost); after sunrise and the descent, the trip continues to the 6th-century St. Catherine's Monastery, a UNESCO World Heritage Site built around the traditional site of the Burning Bush.",
    highlights: [
      "Sunrise from the summit of Mount Sinai",
      "Guided overnight ascent (camel option available)",
      "St. Catherine's Monastery, a UNESCO World Heritage Site",
      "The Chapel of the Burning Bush",
    ],
    included: [
      "Hotel pickup and return",
      "Private air-conditioned transport",
      "Private guide",
      "Entrance fees",
      "Bottled water",
    ],
    excluded: ["Camel ride up the mountain (optional add-on)", "Warm clothing for the summit", "Tips", "Personal spending"],
    price: { amount: null, note: "Ask us for today's rate" },
  },
];

export function getTourBySlug(slug: string) {
  return tours.find((t) => t.slug === slug);
}
